// SPDX-License-Identifier: Apache-2.0
//
// Witness provider for the ShieldedToken contract.
// The private state holds the deployer admin secret key as raw bytes. The
// Compact contract receives it wrapped in an AdminSecretKey struct.

import { Ledger } from "./managed/shielded-token/contract/index.js";
import { WitnessContext } from "@midnight-ntwrk/compact-runtime";

// Private state: just the admin key, generated by the deployer at deploy
// time and kept in local storage thereafter. Never sent to the network.
export type ShieldedTokenPrivateState = {
  readonly adminSecretKey: Uint8Array;
};

export const createShieldedTokenPrivateState = (
  adminSecretKey: Uint8Array
): ShieldedTokenPrivateState => ({
  adminSecretKey
});

// Generate a fresh 32-byte admin secret key. Call once at deploy time.
export const generateAdminSecretKey = (): Uint8Array => {
  const key = new Uint8Array(32);
  crypto.getRandomValues(key);
  return key;
};

// The localSecretKey witness hands the stored private key back to the
// contract every time an admin circuit runs. The contract re-derives the
// public key and checks it against the committed contractAdmin ledger entry.
export const witnesses = {
  localSecretKey: ({
    privateState
  }: WitnessContext<Ledger, ShieldedTokenPrivateState>): [
    ShieldedTokenPrivateState,
    { bytes: Uint8Array }
  ] => [privateState, { bytes: privateState.adminSecretKey }]
};
